import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import fs from 'node:fs';
import test from 'node:test';
import { compileSourceSync } from '../tools/compile-source.mjs';
import { ControlRuntime } from '../runtimes/wasm/control-runtime.mjs';
import {
  PROGRAMMING_BOOK_IMPORT_REVISION,
  deriveProgrammingBookImportPackage,
  verifyProgrammingBookImportPackage,
} from '../tools/generate-programming-book-import-package.mjs';

const root = new URL('../', import.meta.url);
const book = fs.readFileSync(new URL('docs/ProgrammingInGhostflow.md', root), 'utf8');
const englishBook = fs.readFileSync(new URL('docs/ProgrammingInGhostflow.en.md', root), 'utf8');
const baseline = {
  E19: 'ef80061222c5c671b8b78d8fae733b543e51149c7e5d2c7d5e2bb2cc41fbdb30',
  E20: 'bbf57007c5973684660747c515bb2534124d50341647b2282bd2ca32852a724b',
  E21: 'd461a2a0f722271a172ce4c3d66665dad8f3a58a54079712e4bd3adb55f003a0',
};
const englishBaseline = {
  E19: 'b79efd0fad0a4d8ff39ba360dedcc5fc74f6197e760be54316c8811f5488cb8f',
  E20: '328c1224255dc3facd7ef2250fd8ccbf06f31dae48ab50b9e30af84416908247',
};
const inputRevisionBaseline = {
  E19: '7bc10efed87a3db2bbf2e5b56fbf0d6c9a45b54117104d3fa0948baa01f695b4',
  E20: '9928297e43cd7c9790e6ca5178e71f4fd815223654fcd0b16fcc9605ea24bf38',
  E21: '089daea1b525b0be49685b3595554bfb1aa67091fc995da2d65fb0ef9a24357d',
};
const englishInputRevisionBaseline = {
  E19: '945cfec9750a53bcd707f645d37b97d7dc3b6769c63136603dc14047880ba5d9',
  E20: '50c9671fecf17ebe3a693d30ab70ce16cef9a95a320eae5f0728e4a522cb187a',
};
const digest = text => createHash('sha256').update(text).digest('hex');

test('new input revision preserves its separately reviewed E19 and E20 section bytes', () => {
  const derived = deriveProgrammingBookImportPackage(book);
  assert.equal(PROGRAMMING_BOOK_IMPORT_REVISION, 'c8a5d37ac09230a9011291a3ae3b053d1bc22773');
  assert.deepEqual(derived.manifest.imports.map(item => [item.filename, item.revision, item.sha256]), [
    ['E19.ghost.md', PROGRAMMING_BOOK_IMPORT_REVISION, inputRevisionBaseline.E19],
    ['E20.ghost.md', PROGRAMMING_BOOK_IMPORT_REVISION, inputRevisionBaseline.E20],
  ]);
  for (const id of ['E19', 'E20', 'E21']) {
    const start = book.indexOf(`### ${id} —`);
    const end = book.indexOf('\n### ', start + 1);
    assert.equal(derived.files.get(`${id}.ghost.md`), book.slice(start, end), `${id} generated bytes differ from canonical book section`);
  }
});

test('both authored languages preserve the new reviewed E19 and E20 section bytes', () => {
  for (const [document, expected] of [[book, inputRevisionBaseline], [englishBook, englishInputRevisionBaseline]]) {
    for (const id of ['E19', 'E20']) {
      const start = document.indexOf(`### ${id} —`);
      const end = document.indexOf('\n### ', start + 1);
      assert.equal(digest(document.slice(start, end)), expected[id], `${id} reviewed section changed`);
    }
  }
});

test('historical import closure and English sections retain their original identities independently', () => {
  const manifestText = fs.readFileSync(new URL('examples/programming-book-imports/manifest.json', root), 'utf8');
  assert.equal(digest(manifestText), '06aa8e8e78330e4cf7e31b5085db8a8b34e128c703c65867c0871ab7eea38131');
  const manifest = JSON.parse(manifestText);
  const records = [manifest.root, ...manifest.imports,
    ...manifest.compositions.flatMap(item => [item.root, ...item.imports])];
  for (const item of records) {
    const historical = fs.readFileSync(new URL(`examples/programming-book-imports/${item.filename}`, root), 'utf8');
    assert.equal(digest(historical), item.sha256, `${item.filename} historical source identity`);
    if (item.revision) assert.equal(item.revision, '7e135b93ea4c4988d305f992db277a6d8581a271');
  }
  for (const [id, expected] of Object.entries(baseline)) {
    assert.equal(digest(fs.readFileSync(new URL(`examples/programming-book-imports/${id}.ghost.md`, root), 'utf8')), expected);
  }
  for (const [id, expected] of Object.entries(englishBaseline)) {
    assert.equal(digest(fs.readFileSync(new URL(`tests/fixtures/history/issue531/${id}.book.en.pre-input.txt`, root), 'utf8')), expected);
  }
});

test('checked-in package exactly matches deterministic generation', () => {
  const verified = verifyProgrammingBookImportPackage({ repositoryRoot: new URL('.', root) });
  assert.equal(verified.manifest.format, 'GhostFlow/programming-book-import-package-v1');
  assert.equal(verified.manifest.root.filename, 'E22.ghost.md');
  assert.deepEqual([...verified.files.keys()], ['E19.ghost.md', 'E20.ghost.md', 'E21.ghost.md', 'E22.ghost.md', 'E31.ghost.md']);
});

test('E31 pins and composes the explicit input revision of irrigation and ventilation', () => {
  const derived = deriveProgrammingBookImportPackage(book);
  const composition = derived.manifest.compositions[0];
  assert.equal(composition.root.filename, 'E31.ghost.md');
  assert.deepEqual(composition.imports.map(item => item.filename), ['E21.ghost.md', 'E20.ghost.md']);
  const compiled = compileSourceSync(derived.files.get(composition.root.filename), {
    filename: composition.root.filename,
    sourceClosure: composition.imports.map(item => ({
      filename: item.filename,
      revision: item.revision,
      text: derived.files.get(item.filename),
    })),
  });
  assert.deepEqual(compiled.manifest.outputs.map(item => item.name), ['irrigation_demand', 'ventilate_demand']);
  assert.deepEqual(compiled.sourceClosure.documents.map(item => item.filename), ['E20.ghost.md', 'E21.ghost.md']);
});

test('E22 is only import composition and compiles with its exact generated closure', () => {
  const derived = deriveProgrammingBookImportPackage(book);
  const source = derived.files.get('E22.ghost.md');
  assert.doesNotMatch(source, /fn\s+air_vpd|control\s+HumidificationDemand|control\s+VentilationDemand/);
  assert.equal((source.match(/^import /gm) ?? []).length, 2);
  assert.equal((source.match(/^  instance /gm) ?? []).length, 2);
  const compiled = compileSourceSync(source, {
    filename: derived.manifest.root.filename,
    sourceClosure: derived.manifest.imports.map(item => ({
      filename: item.filename,
      revision: item.revision,
      text: derived.files.get(item.filename),
    })),
  });
  assert.deepEqual(compiled.manifest.sensors.map(item => [item.name, item.type]), [
    ['air', 'Temperature'], ['humidity', 'RelativeHumidity'], ['light', 'PPFD'],
  ]);
  assert.deepEqual(compiled.manifest.outputs.map(item => item.name), [
    'air_vpd_value', 'vpd_valid', 'humidify_demand', 'ventilate_demand',
  ]);
  assert.deepEqual(compiled.sourceClosure.documents.map(item => item.filename), ['E19.ghost.md', 'E20.ghost.md']);
});

test('E22 real WASM matches unchanged standalone demands through climate and fault recovery', async t => {
  const derived = deriveProgrammingBookImportPackage(book);
  const closure = derived.manifest.imports.map(item => ({ filename: item.filename, revision: item.revision, text: derived.files.get(item.filename) }));
  const composed = compileSourceSync(derived.files.get('E22.ghost.md'), { filename: 'E22.ghost.md', sourceClosure: closure });
  const high = compileSourceSync(derived.files.get('E19.ghost.md'), { filename: 'E19.ghost.md' });
  const low = compileSourceSync(derived.files.get('E20.ghost.md'), { filename: 'E20.ghost.md' });
  const wasm = fs.readFileSync(new URL('../target/wasm32-unknown-unknown/release/ghostflow_wasm.wasm', import.meta.url));
  const runtimes = await Promise.all([composed, high, low].map(compilation => ControlRuntime.instantiateFramed(wasm, compilation)));
  t.after(() => runtimes.forEach(runtime => runtime.dispose()));
  const frames = [
    { air: 304.15, humidity: 0.45, light: 0.00065, quality: 'Good', expected: [true, false, true] },
    { air: 295.15, humidity: 0.85, light: 0.0005, quality: 'Good', expected: [false, true, true] },
    { air: 295.15, humidity: 0.85, light: 0.0005, quality: 'Invalid', expected: [false, false, false] },
    { air: 304.15, humidity: 0.45, light: 0.00065, quality: 'Good', expected: [true, false, true] },
    { air: 304.15, humidity: 0.45, light: 0, quality: 'Good', expected: [false, false, true] },
  ];
  for (const [index, frame] of frames.entries()) {
    const nowMs = (index + 1) * 1000;
    const samples = Object.fromEntries(['air', 'humidity', 'light'].map(name => [name, {
      epoch: 1, id: index + 1, timestampMs: nowMs, value: frame[name], quality: frame.quality,
    }]));
    const [combined, highOnly, lowOnly] = runtimes.map(runtime => runtime.step({ nowMs, samples }).vm.safe);
    assert.deepEqual(
      [combined.humidify_demand, combined.ventilate_demand, combined.vpd_valid],
      frame.expected,
      `frame ${index} independent demand oracle`,
    );
    assert.equal(combined.humidify_demand, highOnly.humidify_demand, `frame ${index} high demand`);
    assert.equal(combined.ventilate_demand, lowOnly.ventilate_demand, `frame ${index} low demand`);
    assert.equal(combined.air_vpd_value, highOnly.air_vpd_value, `frame ${index} VPD`);
    assert.equal(combined.vpd_valid, highOnly.vpd_valid, `frame ${index} validity`);
  }
});
